steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/gcp-mlops-414802/python-apps/bank-campaign-model', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/gcp-mlops-414802/python-apps/bank-campaign-model']

- name: 'us-central1-docker.pkg.dev/gcp-mlops-414802/python-apps/bank-campaign-model'
  entrypoint: 'bash'
  args:
   - '-c'
   - |
      python -m pytest

- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/ahniverson/model-trainning-repo.git']

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'model-trainning-repo/bank_campaign_model_training.py', 'gs://us-central1-mlops-9244a903-bucket/dags']

images:
- 'us-central1-docker.pkg.dev/gcp-mlops-414802/python-apps/bank-campaign-model'

options:
  logging: CLOUD_LOGGING_ONLY
